# Generated by Django 6.0.2 on 2026-07-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Description for the caption and alt text', max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which it appears (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='A Physical Board Game by Amna Noor', max_length=100)),
                ('hero_title', models.CharField(default='RHIZOMATA', max_length=100)),
                ('hero_subtitle', models.TextField(default='Where Roots Become Destiny.\nEvery decision echoes. Every element reacts.')),
                ('about_quote', models.TextField(default='In the rhizome, there is no beginning or end — only the middle, from which it grows and overflows.')),
                ('about_intro', models.TextField(default='Rhizomata is a philosophical strategy game rooted in the ancient Greek concept of interconnected elements — earth, water, fire, and air — reimagined as a premium physical experience.')),
                ('contact_email', models.EmailField(default='info@rhizomata.com', max_length=254)),
                ('instagram_url', models.URLField(blank=True, help_text='Link to your Instagram profile', null=True)),
                ('core_set_price', models.DecimalField(decimal_places=2, default=79.0, max_digits=6)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
