# Generated by Django 6.0.6 on 2026-07-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('identity', 'Identity Card'), ('situation', 'Situation Card'), ('context', 'Context Card')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('front_image', models.ImageField(upload_to='cards/')),
                ('back_image', models.ImageField(upload_to='cards/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GamePawn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pawns/')),
                ('title_color_class', models.CharField(default='text-orange-400', max_length=50)),
                ('glow_color', models.CharField(default='rgba(209,104,52,0.15)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PreviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or description of the preview', max_length=200)),
                ('image', models.ImageField(upload_to='previews/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='board_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='board_label',
            field=models.CharField(default='The Arena', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='board_text',
            field=models.TextField(default='The game board is a cyclical track representing the life cycle of a civilization, moving from the Golden Age to the Iron Age. As the eras change, the fundamental rules of survival shift with them.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='board_title',
            field=models.CharField(default='The <span class="gradient-text">Board</span>', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='concept_author',
            field=models.CharField(default='— Created by Amna Noor', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='concept_label',
            field=models.CharField(default='The Philosophy', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='concept_text_1',
            field=models.TextField(default='Most games use chance - dice, card draws, random events - as the primary engine of excitement. <strong>Rhizomata</strong> proposes a different approach: <strong>all consequences are visible before every choice is made.</strong>'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='concept_text_2',
            field=models.TextField(default='There are no hidden reveals, no dice, no luck in the result of any decision. The tension is not informational. It is moral. Every person is a hostage to what they have earned.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='concept_title',
            field=models.CharField(default='Destiny is not given.<br /><span class="gradient-text">It is chosen.</span>', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='context_label',
            field=models.CharField(default='The Variables', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='context_text',
            field=models.TextField(default='But choices are rarely made in a vacuum. The Context Cards shift the environment, forcing players to adapt to external pressures beyond their control. A decision that seemed easy in times of peace becomes devastating during a famine or a plague.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='context_title',
            field=models.CharField(default='Context <span class="gradient-text">Cards</span>', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='how_to_play_label',
            field=models.CharField(default='Rules of the Realm', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='how_to_play_title',
            field=models.CharField(default='How to Play', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='identity_label',
            field=models.CharField(default='The Elements', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='identity_text',
            field=models.TextField(default='In classical philosophy, your element is assigned at birth — fixed, inherited, and beyond your control. Rhizomata challenges this. The element is dealt randomly at the start of the game, but what you do with it is entirely a matter of choice. It is a starting condition, not a sentence.<br><br><span style="color: var(--accent); font-style: italic;">Click a card to reveal its true identity.</span>'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='identity_title',
            field=models.CharField(default='Identity <span class="gradient-text">Cards</span>', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pawns_label',
            field=models.CharField(default='The Duality', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pawns_text',
            field=models.TextField(default='Every player controls two interconnected pawns, representing the fundamental duality of human nature: Ambition and Stability. One reaches for greatness at great cost. The other seeks security, but risks stagnation.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pawns_title',
            field=models.CharField(default='The <span class="gradient-text">Pawns</span>', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rule_1_text',
            field=models.TextField(default='You control two pawns simultaneously. The <strong>Stability Pawn</strong> moves ahead for grounded, restrained choices. The <strong>Ambition Pawn</strong> moves ahead for bold, risky decisions.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rule_1_title',
            field=models.CharField(default='1. The Dual-Self', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rule_2_text',
            field=models.TextField(default='There are no dice. Every Situation Card and Context Card shows the <em>exact consequences</em> of both options before you choose. The tension is not informational—it is moral.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rule_2_title',
            field=models.CharField(default='2. Visible Consequences', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rule_3_text',
            field=models.TextField(default='Your choices reward you with Balance or Pressure tokens. These tokens are a permanent record of the kind of actions you took. Choose wisely; they cannot be undone.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rule_3_title',
            field=models.CharField(default='3. The Token Economy', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rulebook_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='situation_label',
            field=models.CharField(default='The Dilemmas', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='situation_text',
            field=models.TextField(default='The tension between who we want to be and who we actually become in moments of pressure is the core of the game. You will face 60 unique moral decisions. Both options display their full consequences before you decide. No dice. No luck. <br><br><span style="color: var(--accent); font-style: italic;">Click to face your fate.</span>'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='situation_title',
            field=models.CharField(default='Situation <span class="gradient-text">Cards</span>', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_1_label',
            field=models.CharField(default='Unique Cards', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_1_number',
            field=models.CharField(default='102', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_2_label',
            field=models.CharField(default='Elemental Realms', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_2_number',
            field=models.CharField(default='4', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_3_label',
            field=models.CharField(default='Max Players', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_3_number',
            field=models.CharField(default='4', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_4_label',
            field=models.CharField(default='Minutes of Play', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_4_number',
            field=models.CharField(default='<span data-count="60" id="stat-time-num">60</span><span style="font-size:0.55em;opacity:0.7;">-90</span>', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_intro',
            field=models.TextField(default='Rhizomata is a tabletop board game built around a single design question: what happens when a player can see the full consequence of every choice before making it?\n\nThe game draws on the elemental philosophy of Empedocles (circa 490-430 BCE), who proposed that all reality is composed of four fundamental roots — fire, water, air, and earth — governed by Love and Strife.\n\nThere are no dice. No hidden reveals. The tension is entirely moral. You define yourself through what you choose.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_quote',
            field=models.TextField(default='Khudi ko kar buland itna ke har taqdeer se pehle,\nKhuda bande se khud poochhe, bata teri raza kya hai.\n— Allama Muhammad Iqbal'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='info@rhizomata.net', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_eyebrow',
            field=models.CharField(default='A Tabletop Board Game Design by Amna Noor', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(default='Destiny is not given. It is chosen.\nThe tension is not informational. It is moral.'),
        ),
    ]
