# Generated by Django 6.0.6 on 2026-07-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gamecard_gamepawn_previewimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='conclusion_text',
            field=models.TextField(default='Rhizomata does not end with a score. After tallying your tokens and pawn positions across the two-axis matrix, the game ends with the <strong>Archetype Reveal</strong>.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='conclusion_title',
            field=models.CharField(default='No Winners, No Losers', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sub_conclusion_text',
            field=models.TextField(default='You leave the table with a character, not a number: <em>The Sage, The Guardian, The Wanderer, The Rebel,</em> or <em>The Opportunist</em>. The game does not judge you; it simply reflects the record of your own choices.'),
        ),
    ]
